"use client";
import { useMemo, useState } from "react";
const mutations=[{label:"None",value:"1",note:"No mutation modifier"},{label:"Silver",value:"1.25",note:"Community-reported preset"},{label:"Bloom",value:"1.5",note:"Community-reported preset"},{label:"Golden",value:"2",note:"Community-reported preset"},{label:"Rainbow",value:"2.5",note:"Community-reported preset"},{label:"Spirit Bloom",value:"3",note:"Sources disagree; edit if your game shows another value"},{label:"Custom",value:"custom",note:"Enter the multiplier shown in your game"}] as const;
type Inputs={name:string;base:string;size:string;mutation:string;custom:string};
const startA:Inputs={name:"Current pet",base:"4000",size:"1",mutation:"1",custom:"1"};
const startB:Inputs={name:"New pet",base:"",size:"1",mutation:"1",custom:"1"};
const number=(value:string)=>{const result=Number(value);return Number.isFinite(result)?result:NaN};
function calculate(value:Inputs){const base=number(value.base),size=number(value.size),mutation=number(value.mutation==="custom"?value.custom:value.mutation);const valid=base>=0&&size>0&&mutation>0;const second=valid?base*size*mutation:0;return{base,size,mutation,valid,second,minute:second*60,hour:second*3600}}
const format=(value:number)=>new Intl.NumberFormat("en-US",{maximumFractionDigits:2,notation:value>=1_000_000?"compact":"standard"}).format(value);
function Fields({id,value,onChange}:{id:string;value:Inputs;onChange:(next:Inputs)=>void}){const set=(key:keyof Inputs,next:string)=>onChange({...value,[key]:next});const selected=mutations.find(item=>item.value===value.mutation);return <fieldset className="calculator-panel"><legend>{id==="a"?"Pet A":"Pet B (optional)"}</legend><label><span>Label</span><input value={value.name} onChange={e=>set("name",e.target.value)}/></label><label><span>Base cash per second</span><input inputMode="decimal" min="0" type="number" value={value.base} onChange={e=>set("base",e.target.value)} placeholder={id==="a"?"4000":"Leave empty to compare later"}/></label><label><span>Size multiplier</span><input inputMode="decimal" min="0.01" step="0.01" type="number" value={value.size} onChange={e=>set("size",e.target.value)}/></label><label><span>Mutation</span><select value={value.mutation} onChange={e=>set("mutation",e.target.value)}>{mutations.map(item=><option key={item.label} value={item.value}>{item.label} ({item.value==="custom"?"editable":`${item.value}×`})</option>)}</select></label>{value.mutation==="custom"&&<label><span>Custom mutation multiplier</span><input inputMode="decimal" min="0.01" step="0.01" type="number" value={value.custom} onChange={e=>set("custom",e.target.value)}/></label>}<p className="field-note">{selected?.note}</p></fieldset>}
export function CalculatorTool(){const[petA,setPetA]=useState(startA);const[petB,setPetB]=useState(startB);const a=useMemo(()=>calculate(petA),[petA]);const b=useMemo(()=>calculate(petB),[petB]);const comparing=petB.base.trim()!==""&&b.valid;const lead=comparing?(b.second>a.second?petB.name||"Pet B":b.second<a.second?petA.name||"Pet A":"Tie"):null;const difference=comparing?Math.abs(b.second-a.second):0;const lower=comparing?Math.min(a.second,b.second):0;const advantage=lower>0?difference/lower*100:null;return <div className="calculator-shell"><div className="calculator-input-grid"><Fields id="a" value={petA} onChange={setPetA}/><Fields id="b" value={petB} onChange={setPetB}/></div>{!a.valid?<p className="calculator-error" role="alert">Enter a base value of zero or more and multipliers above zero.</p>:<section className="calculator-result" aria-live="polite"><div><span>Cash / second</span><strong>${format(a.second)}</strong></div><div><span>Cash / minute</span><strong>${format(a.minute)}</strong></div><div><span>Cash / hour</span><strong>${format(a.hour)}</strong></div><p>{petA.name||"Pet A"}: ${format(a.base)} × {a.size} size × {a.mutation} mutation = ${format(a.second)} per second.</p>{comparing&&<p className="comparison-callout">{lead==="Tie"?"Both setups earn the same amount.":<><strong>{lead}</strong> leads by ${format(difference)} per second{advantage===null?".":` (${format(advantage)}%).`}</>}</p>}</section>}<p className="calculator-source-note">Presets are community-reported values checked September 8, 2026. If the number shown in your game differs, choose Custom. This tool estimates passive cash, not trade value or hatch odds.</p></div>}
