import Link from "next/link";
import { AdsterraArticleBottom, AdsterraArticleMid, AdsterraArticleTop } from "@/components/ads";
import { BreadcrumbJsonLd, FaqJsonLd } from "@/components/seo/JsonLd";
import { Breadcrumbs, PageIntro, SectionHeader } from "@/components/ui/content";
export type GuideEntry={name:string;meta:string;value?:string;note:string}; export type GuideFaq={question:string;answer:string};
export type EntityGuide={eyebrow:string;title:string;description:string;route:string;parent:{label:string;href:string};checked:string;notice:string;answer:string;intro:string[];entries:GuideEntry[];stepsTitle:string;steps:string[];cautions:string[];faqs:GuideFaq[];links:{href:string;label:string;note:string}[]};
export function EntityLanding({guide}:{guide:EntityGuide}){const faqItems=guide.faqs.map(x=>({q:x.question,a:x.answer}));return <main className="mx-auto max-w-7xl px-4 py-10">
<BreadcrumbJsonLd items={[{name:"Home",href:"/"},{name:guide.parent.label,href:guide.parent.href},{name:guide.title,href:guide.route}]}/><FaqJsonLd items={faqItems}/><Breadcrumbs items={[{label:guide.parent.label,href:guide.parent.href},{label:guide.title,href:guide.route}]}/>
<PageIntro eyebrow={guide.eyebrow} title={guide.title} description={guide.description}><div className="flex flex-wrap gap-2"><span className="status-pill">Checked {guide.checked}</span><span className="status-pill">Independent guide</span></div></PageIntro><AdsterraArticleTop/>
<section className="mt-10 grid gap-4 lg:grid-cols-[1.25fr_.75fr]"><article className="content-card"><SectionHeader eyebrow="Quick answer" title={guide.answer}/><div className="mt-5 grid gap-4 text-sm leading-7 text-white/72">{guide.intro.map(p=><p key={p}>{p}</p>)}</div></article><aside className="content-card"><span className="mini-label">Data note</span><p className="mt-4 text-sm leading-7 text-white/70">{guide.notice}</p></aside></section>
<section className="mt-12"><SectionHeader eyebrow="Current records" title="What the checked sources show"/><div className="mt-6 grid gap-4 md:grid-cols-2">{guide.entries.map(x=><article className="content-card" key={x.name}><div className="flex items-start justify-between gap-4"><div><h2 className="text-xl font-extrabold text-white">{x.name}</h2><p className="mt-1 text-xs uppercase tracking-wider text-white/45">{x.meta}</p></div>{x.value&&<span className="status-pill">{x.value}</span>}</div><p className="mt-4 text-sm leading-6 text-white/68">{x.note}</p></article>)}</div></section><AdsterraArticleMid/>
<section className="mt-12 grid gap-4 lg:grid-cols-2"><article className="content-card"><SectionHeader eyebrow="Player route" title={guide.stepsTitle}/><ol className="mt-5 grid gap-3 text-sm leading-6 text-white/70">{guide.steps.map((x,i)=><li key={x}><strong className="text-[color:var(--accent)]">{i+1}.</strong> {x}</li>)}</ol></article><article className="content-card"><SectionHeader eyebrow="Avoid mistakes" title="What this guide does not assume"/><ul className="mt-5 grid gap-3 text-sm leading-6 text-white/70">{guide.cautions.map(x=><li key={x}>• {x}</li>)}</ul></article></section>
<section className="mt-12"><SectionHeader eyebrow="FAQ" title="Common questions"/><div className="mt-6 grid gap-4">{guide.faqs.map(x=><details className="content-card" key={x.question}><summary className="cursor-pointer font-bold text-white">{x.question}</summary><p className="mt-3 text-sm leading-7 text-white/68">{x.answer}</p></details>)}</div></section>
<section className="mt-12"><SectionHeader eyebrow="Keep exploring" title="Related Steal An Egg guides"/><div className="mt-6 grid gap-4 md:grid-cols-3">{guide.links.map(x=><Link className="content-card" href={x.href} key={x.href}><h2 className="font-bold text-white">{x.label}</h2><p className="mt-2 text-sm text-white/60">{x.note}</p></Link>)}</div></section><AdsterraArticleBottom/></main>}
